### ISSUE TITLE
One error: Digest method not supported

### ISSUE THREAD

**Issue by xietao1233** [planttheidea/fast-copy#19]
```javascript
const _ = require('lodash');
const Copy = require('fast-copy');

const hash = Crypto.createHash('sha256');
hash.update(sendPacketData);
//let newHash = _.cloneDeep(hash);      //success
let newHash = Copy(hash, {isStrict: true});  //failed
newHash.update(item.data);
```
    at getObjectCloneStrict (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:114:36)
    at handleCopy (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:286:16)
    at copy (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:288:12)
    at d:\src\node\WechatWrap\test\testPacketDecrypt.js:59:23
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (d:\src\node\WechatWrap\test\testPacketDecrypt.js:54:9)
    at Module._compile (internal/modules/cjs/loader.js:686:14)
Waiting for the debugger to disconnect...
Error: Digest method not supported
utils.ts:70
    at getCleanClone (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:56:16)
    at getObjectCloneStrict (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:105:17)
    at handleCopy (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:286:16)
    at getObjectCloneStrict (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:114:36)
    at handleCopy (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:286:16)
    at copy (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:288:12)
    at d:\src\node\WechatWrap\test\testPacketDecrypt.js:59:23
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (d:\src\node\WechatWrap\test\testPacketDecrypt.js:54:9)
    at Module._compile (internal/modules/cjs/loader.js:686:14)

**Comment by planttheidea** [comment]
Should be fixed as-of `2.0.3`. If you have any more issues, let me know!
