### ISSUE TITLE
Function.prototype.toString requires that 'this' be a Function

### ISSUE THREAD

**Issue by chrisands** [planttheidea/fast-copy#94]
Here from pinojs/pino-pretty#477

Basically I get an error from trying to log null object that uses V8 optimization
```
TypeError: Function.prototype.toString requires that 'this' be a Function
    at toString (<anonymous>)
    at getCleanClone (/Users/osiyuk/Projects/github/pino-pretty-issue/node_modules/.pnpm/fast-copy@3.0.1/node_modules/fast-copy/dist/cjs/index.cjs:49:27)
    at copyObjectLooseModern (/Users/osiyuk/Projects/github/pino-pretty-issue/node_modules/.pnpm/fast-copy@3.0.1/node_modules/fast-copy/dist/cjs/index.cjs:213:17)
    at copier (/Users/osiyuk/Projects/github/pino-pretty-issue/node_modules/.pnpm/fast-copy@3.0.1/node_modules/fast-copy/dist/cjs/index.cjs:362:20)
    at copy (/Users/osiyuk/Projects/github/pino-pretty-issue/node_modules/.pnpm/fast-copy@3.0.1/node_modules/fast-copy/dist/cjs/index.cjs:375:16)
    at filterLog (/Users/osiyuk/Projects/github/pino-pretty-issue/node_modules/.pnpm/pino-pretty@10.2.3/node_modules/pino-pretty/lib/utils/filter-log.js:30:19)
    at Object.pretty (/Users/osiyuk/Projects/github/pino-pretty-issue/node_modules/.pnpm/pino-pretty@10.2.3/node_modules/pino-pretty/lib/pretty.js:81:11)
    at Object.<anonymous> (/Users/osiyuk/Projects/github/pino-pretty-issue/index.js:18:14)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
```

Optimization looks like this and it used in `fast-querystring` package
```
// Optimization: Use new Empty() instead of Object.create(null) for performance
// v8 has a better optimization for initializing functions compared to Object
const Empty = function () {};
Empty.prototype = Object.create(null);
```

I figured out that internal function `getCleanClone` only check that prototype exist
```
  if (!prototype) {
    return create(null);
  }
```
I think it should handle case where `var Constructor = prototype.constructor === undefined` that would mean that this is null prototype and we should return `create(null)`. I could make PR if you agree with it. What do you think? 

Also it possible to use this optimization, but I'm not sure how much it would be breaking change and should be perf tested to understand if this is worth it. Separate issue ofc.

**Comment by planttheidea** [comment]
Yeah feel free to make a PR, seems like a cheap check for added safety. I'm assuming something like this?

```ts
if (!prototype || !prototype.constructor) {
  return create(null);
}
```

**Comment by planttheidea** [comment]
Version `3.0.2` has been released with this fix. If you have any more issues, let me know!
